# .gitlab-ci.yml

# Define stages for the pipeline
stages:
  - build

# Define jobs for each stage
build:
  stage: build
  script:
    # Build the Docker image
    - docker build -t my-nginx-image .
    # (Optional) Tag the image with GitLab CI/CD variables
    # - docker tag my-nginx-image $CI_REGISTRY_IMAGE:latest
    # Push the Docker image to GitLab Container Registry (if needed)
    # - docker push $CI_REGISTRY_IMAGE:latest
  tags:
    - docker   # Specify a runner with Docker support
  artifacts:
    paths:
      - Dockerfile   # Include Dockerfile as an artifact

