# .gitlab-ci.yml

stages:
  - build

variables:
  DOCKER_HOST: "tcp://docker:2375"  # Set Docker host to the Docker-in-Docker service
  
default:
  image: docker:latest
  services:
  - docker:dind

build:
  stage: build
  tags: 
    - runner
  before_script:
    - docker version
  script:
    - docker info
    - docker login registry.gitlab.com -u GurlovleenSingh -p $TOKEN
    - docker build -t registry.gitlab.com/project1740/ngnix_project .
    - docker push registry.gitlab.com/project1740/ngnix_project

