# .gitlab-ci.yml

stages:
  - build
  - test

variables:
  DOCKER_HOST: tcp://docker:2375/  # Set Docker host to the Docker-in-Docker service

services:
  - docker:dind

build:
  stage: build
  script:
    - docker info
    - docker build -t my-docker-image .

test:
  stage: test
  script:
    - docker run my-docker-image /bin/bash -c "your test command here"
